#!/usr/bin/env python3
"""Speak every drop script in a folder. No Claude, no API key.

The station only ever reads .wav files, so where the words came from is your
business — hand-written, pasted out of a chat window, generated by a local
model, whatever. Put one drop per .txt file in the time band it belongs to
(night / morning / afternoon / evening, or anytime for evergreen lines):

    drops/today/night/quiet-hours.txt
    drops/today/morning/09-track-credit.txt
    drops/today/anytime/station-id.txt

then:

    python3 scripts/speak_drops.py            # speak anything missing a .wav
    python3 scripts/speak_drops.py --force    # re-speak everything

Skips any .txt that already has a matching .wav, so it's cheap to re-run after
editing one line.
"""

from __future__ import annotations

import argparse
import pathlib
import sys

sys.path.insert(0, str(pathlib.Path(__file__).parent))
from tts import PROVIDER, speak  # noqa: E402

ROOT = pathlib.Path(__file__).resolve().parent.parent


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("folder", nargs="?", default=str(ROOT / "drops" / "today"))
    ap.add_argument("--force", action="store_true", help="re-speak drops that already have audio")
    args = ap.parse_args()

    folder = pathlib.Path(args.folder)
    if not folder.is_dir():
        print(f"No such folder: {folder}", file=sys.stderr)
        return 1

    scripts = sorted(folder.rglob("*.txt"))
    if not scripts:
        print(f"No .txt drops in {folder}. Write some first.", file=sys.stderr)
        return 1

    spoken = skipped = 0
    for script in scripts:
        wav = script.with_suffix(".wav")
        if wav.exists() and not args.force:
            skipped += 1
            continue
        text = script.read_text().strip()
        if not text:
            print(f"  (empty, skipping) {script.name}")
            continue
        label = f"{script.parent.name}/{script.stem}"
        print(f"  {label}  {text[:70]}{'…' if len(text) > 70 else ''}")
        speak(text, wav)
        spoken += 1

    print(f"\nSpoke {spoken} via '{PROVIDER}', skipped {skipped} already done.")
    if skipped and not args.force:
        print("Use --force to re-speak the rest.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
